export const APP_DB = {
    'Code.exe': { name: 'VS Code', emoji: ':computer:', category: 'coding' },
    Code: { name: 'VS Code', emoji: ':computer:', category: 'coding' },
    code: { name: 'VS Code', emoji: ':computer:', category: 'coding' },
    Cursor: { name: 'Cursor', emoji: ':computer:', category: 'coding' },
    'cursor.exe': { name: 'Cursor', emoji: ':computer:', category: 'coding' },
    'idea64.exe': { name: 'IntelliJ IDEA', emoji: ':computer:', category: 'coding' },
    idea: { name: 'IntelliJ IDEA', emoji: ':computer:', category: 'coding' },
    'pycharm64.exe': { name: 'PyCharm', emoji: ':snake:', category: 'coding' },
    'clion64.exe': { name: 'CLion', emoji: ':computer:', category: 'coding' },
    nvim: { name: 'Neovim', emoji: ':computer:', category: 'coding' },
    vim: { name: 'Vim', emoji: ':computer:', category: 'coding' },
    Xcode: { name: 'Xcode', emoji: ':computer:', category: 'coding' },
    'sublime_text.exe': { name: 'Sublime Text', emoji: ':computer:', category: 'coding' },
    sublime_text: { name: 'Sublime Text', emoji: ':computer:', category: 'coding' },
    'studio64.exe': { name: 'Android Studio', emoji: ':robot_face:', category: 'coding' },
    studio: { name: 'Android Studio', emoji: ':robot_face:', category: 'coding' },
    'webstorm64.exe': { name: 'WebStorm', emoji: ':computer:', category: 'coding' },
    webstorm: { name: 'WebStorm', emoji: ':computer:', category: 'coding' },
    'rider64.exe': { name: 'Rider', emoji: ':computer:', category: 'coding' },
    rider: { name: 'Rider', emoji: ':computer:', category: 'coding' },
    'eclipse.exe': { name: 'Eclipse', emoji: ':computer:', category: 'coding' },
    eclipse: { name: 'Eclipse', emoji: ':computer:', category: 'coding' },
    'WindowsTerminal.exe': { name: 'Windows Terminal', emoji: ':terminal:', category: 'coding' },
    Terminal: { name: 'Terminal', emoji: ':terminal:', category: 'coding' },
    iTerm2: { name: 'iTerm', emoji: ':terminal:', category: 'coding' },
    'Unity.exe': { name: 'Unity', emoji: ':video_game:', category: 'coding' },
    Unity: { name: 'Unity', emoji: ':video_game:', category: 'coding' },
    'UnrealEditor.exe': { name: 'Unreal Engine', emoji: ':video_game:', category: 'coding' },
    UnrealEditor: { name: 'Unreal Engine', emoji: ':video_game:', category: 'coding' },

    'figma.exe': { name: 'Figma', emoji: ':art:', category: 'design' },
    Figma: { name: 'Figma', emoji: ':art:', category: 'design' },
    Sketch: { name: 'Sketch', emoji: ':pencil:', category: 'design' },
    'blender.exe': { name: 'Blender', emoji: ':art:', category: 'design' },
    blender: { name: 'Blender', emoji: ':art:', category: 'design' },
    'Photoshop.exe': { name: 'Photoshop', emoji: ':art:', category: 'design' },
    Photoshop: { name: 'Photoshop', emoji: ':art:', category: 'design' },

    'Spotify.exe': { name: 'Spotify', emoji: ':spotify_logo:', category: 'music' },
    Spotify: { name: 'Spotify', emoji: ':spotify_logo:', category: 'music' },
    spotify: { name: 'Spotify', emoji: ':spotify_logo:', category: 'music' },
    Music: { name: 'Apple Music', emoji: ':musical_note:', category: 'music' },
    'foobar2000.exe': { name: 'foobar2000', emoji: ':musical_note:', category: 'music' },

    'EpicGamesLauncher.exe': { name: 'Epic Games', emoji: ':video_game:', category: 'game' },
    'LeagueClient.exe': { name: 'League of Legends', emoji: ':crossed_swords:', category: 'game' },
    'VALORANT-Win64-Shipping.exe': { name: 'Valorant', emoji: ':dart:', category: 'game' },

    'Resolve.exe': { name: 'DaVinci Resolve', emoji: ':movie_camera:', category: 'media' },
    Resolve: { name: 'DaVinci Resolve', emoji: ':movie_camera:', category: 'media' },
    'obs64.exe': { name: 'OBS', emoji: ':movie_camera:', category: 'media' },
    obs: { name: 'OBS', emoji: ':movie_camera:', category: 'media' },

    'Discord.exe': { name: 'Discord', emoji: ':speech_balloon:', category: 'meeting' },
    Discord: { name: 'Discord', emoji: ':speech_balloon:', category: 'meeting' },
    'Zoom.exe': { name: 'Zoom', emoji: ':video_camera:', category: 'meeting' },
    zoom: { name: 'Zoom', emoji: ':video_camera:', category: 'meeting' },
    'Teams.exe': { name: 'Microsoft Teams', emoji: ':video_camera:', category: 'meeting' },
    Teams: { name: 'Microsoft Teams', emoji: ':video_camera:', category: 'meeting' },
};

export const CATEGORY_PRIORITY = ['meeting', 'game', 'coding', 'music', 'design', 'media'];
